importtoexportdjango/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from main.views import HomeView, CategoryView, NewsDetailView, VideosView
from django.conf.urls import *
from django.http import HttpResponse
from main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.landing, name="landing"),
    url(r'^home/$', HomeView.as_view(), name="home"),
    url(r'^videos', VideosView.as_view(), name="videos_view"),
    url(r'^(?P<slug>[\w\-]+)/$', CategoryView.as_view(), name="category_view"),
    #url(r'^noticia/(?P<slug>[\w\-]+)/$', NewsDetailView.as_view(), name="news_detail"),
    #url(r'^(?P<catslug>[\w\-]+)/(?P<slug>[\w\-]+)/$', NewsDetailView.as_view(), name="news_detail"),
    url(r'^(?P<category>[\w\-]+)/(?P<slug>[\w\-]+)/$', NewsDetailView.as_view(), name="news_detail"),
    url(r'^suscripcion', views.contactUs, name="suscripcion"),
    url(r'^franquiciatario', views.franquiciatario, name="franquiciatario"),
    url(r'^search_news', views.search_news, name='search_news'),
    url(r'^resultado-de-busqueda', views.resultado_de_busqueda, name='resultado_de_busqueda'),
    url(r'^aviso-de-privacidad', views.terms_and_conditions, name='terms_and_conditions'),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.append(url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

main/models.py
from __future__ import unicode_literals

from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.template.defaultfilters import slugify
from autoslug import AutoSlugField

# Create your models here.


class Test(models.Model):
    date = models.DateField()
    title = models.TextField()

class Author(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

class Book(models.Model):
    name = models.CharField('Book name', max_length=100)
    author = models.ForeignKey(Author, blank=True, null=True)
    author_email = models.EmailField('Author email', max_length=75, blank=True)
    imported = models.BooleanField(default=False)
    published = models.DateField('Published', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    categories = models.ManyToManyField(Category, blank=True)

    def __unicode__(self):
        return self.name

class PromotionBanner(models.Model):
    titulo = models.CharField(max_length=100, blank=True)
    banner_url = models.CharField(max_length=1000, blank=True)
    banner_image = models.ImageField(upload_to='Images/PromotionBanners/')
    def __unicode__(self):
        return self.titulo

class BannerInSection(models.Model):
    titulo = models.CharField(max_length=100, blank=True)
    def __unicode__(self):
        return self.titulo

class BannerItem(models.Model):
    titulo = models.CharField(max_length=50,blank=True,null=True)
    descripcion = models.CharField(max_length=250, blank=True)
    slide_url = models.CharField(max_length=500, blank=True)
    image = models.ImageField(upload_to='Images/Benner/Items/')
    banner_in_section = models.ForeignKey(BannerInSection, blank=True, null=True)
    def __unicode__(self):
        return self.titulo

class SectionSlide(models.Model):
    nombre = models.CharField(max_length=100, blank=True)
    def __unicode__(self):
        return self.nombre

class SectionSlideItem(models.Model):
    titulo = models.CharField(max_length=50,blank=True,null=True)
    descripcion = models.CharField(max_length=250, blank=True)
    slide_url = models.CharField(max_length=500, blank=True)
    image = models.ImageField(upload_to='Images/Section/Slide/')
    section_slide = models.ForeignKey(SectionSlide, blank=True, null=True)
    def __unicode__(self):
        return self.titulo

class Tag(models.Model):
    name = models.CharField('Tags name', max_length=100)

    def __unicode__(self):
        return self.name

class Metatag(models.Model):
    titulo = models.CharField(max_length=100,blank=True)
    descripcion = models.CharField(max_length=1000,blank=True)
    keywords = models.CharField(max_length=1000,blank=True)
    def __unicode__(self):
        return self.titulo

class Video(models.Model):
    titulo = models.CharField(max_length=200, blank=True)
    descripcion = RichTextField(max_length=10000, blank=True, null=True)
    id_video = models.CharField(max_length=20, blank=True)

class Section(models.Model):
    titulo = models.CharField('Nombre de Seccion', max_length=100)
    descripcion = RichTextField(max_length=10000, blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    section_slide = models.ForeignKey(SectionSlide, blank=True, null=True)
    banner = models.ForeignKey(BannerInSection, blank=True, null=True)
    promotion_banner = models.ForeignKey(PromotionBanner, blank=True, null=True)
    metatag = models.ForeignKey(Metatag, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.titulo)
        super(Section, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.titulo

class CategoryNew(models.Model):
    name = models.CharField('Nombre de Categoria', max_length=100)
    slug = models.SlugField(unique=True, blank=True, null=True)
    category_slide = models.ForeignKey(SectionSlide, blank=True, null=True)
    banner = models.ForeignKey(BannerInSection, blank=True, null=True)
    metatag = models.ForeignKey(Metatag, blank=True, null=True)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(CategoryNew, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class New(models.Model):
    titulo = models.CharField('News name', max_length=10000)
    categoria = models.ForeignKey(CategoryNew, related_name='children')
    imagen_thumbnail = models.ImageField(upload_to="images", blank=True, null=True)
    imagen_slide = models.ImageField(upload_to="images", blank=True, null=True)
    imagen1 = models.ImageField(upload_to="images", blank=True, null=True)
    sumario = models.TextField(max_length=10000, blank=True, null=True)
    texto1 = RichTextField(max_length=10000, blank=True, null=True)
    imagen2 = models.ImageField(upload_to="images", blank=True, null=True)
    texto2 = models.TextField(max_length=10000, blank=True, null=True)
    destacado1 = models.TextField(max_length=10000, blank=True, null=True)
    texto3 = models.TextField(max_length=10000, blank=True, null=True)
    imagen3 = models.ImageField(upload_to="images", blank=True, null=True)
    texto4 = models.TextField(max_length=10000, blank=True, null=True)
    destacado2 = models.TextField(max_length=10000, blank=True, null=True)
    texto5 = models.TextField(max_length=10000, blank=True, null=True)
    imagen4 = models.ImageField(upload_to="images", blank=True, null=True)
    texto6 = models.TextField(max_length=10000, blank=True, null=True)
    texto7 = models.TextField(max_length=10000, blank=True, null=True)
    imagen5 = models.ImageField(upload_to="images", blank=True, null=True)
    etiquetas = models.TextField(max_length=200, blank=True, null=True)
    date = models.DateField('Published', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    #slug = AutoSlugField(populate_from=titulo, unique_with='categoria_slug',blank=True, null=True, editable=True)
    metatag = models.ForeignKey(Metatag, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.titulo)
        super(New, self).save(*args, **kwargs)

    def get_previous(self):
        """
        Returns the previous element of the list using the current index if it exists.
        Otherwise returns an empty string.
        """
        previous = self.__class__.objects.filter(pk__lt=self.pk).order_by('-pk')
        try:
            return previous[0]
        except IndexError:
            return False

    def get_next(self):
        """
        Get the next object by primary key order
        """
        next = self.__class__.objects.filter(pk__gt=self.pk)
        try:
            return next[0]
        except IndexError:
            return False

    def __unicode__(self):
        return self.titulo

class NewsLetterSuscription(models.Model):
    correo_electronico = models.TextField(max_length=100, blank=True, null=True)
    def __unicode__(self):
        return self.correo_electronico

class Contacto(models.Model):
    nombre_contacto = models.CharField(max_length=100)
    sexo = models.CharField(max_length=100)
    edad = models.CharField(max_length=10)
    ciudad = models.CharField(max_length=100)
    estado = models.CharField(max_length=100)
    empresa = models.CharField(max_length=100)
    correo_electronico = models.CharField(max_length=150,blank=True,null=True)

    def __unicode__(self):
        return self.nombre_contacto

class Franquiciatario(models.Model):
    nombre_contacto = models.CharField(max_length=200,blank=True,null=True)
    correo_electronico = models.CharField(max_length=150,blank=True,null=True)
    telefono = models.CharField(max_length=100,blank=True,null=True)
    comentario = models.CharField(max_length=1500,blank=True,null=True)    

    def __unicode__(self):
        return self.nombre_contacto

main/forms.py
from django import forms

class FormBuscarElementos(forms.Form):
	term = forms.CharField(max_length=100)

class Contacto(forms.Form):
    user_name = forms.CharField(max_length=100, required=True)
    user_sex = forms.CharField(required=True, max_length=13)
    user_age = forms.CharField(max_length=80)
    user_city = forms.CharField(max_length=80)
    user_state = forms.CharField(max_length=80)
    user_email = forms.EmailField(required=True)

class Franquiciatario(forms.Form):
    user_name = forms.CharField(max_length=100, required=True)
    user_email = forms.EmailField(required=True)
    user_phone_number = forms.CharField(required=True, max_length=13)
    user_message = forms.CharField(widget=forms.Textarea, max_length=250)

main/templates/category.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block bodyclass %}qpsp-{{ section.slug }}{% endblock %}

{% block title %}{{ section.metatag.titulo }}{% endblock %}
{% block site_title %}{{section.metatag.titulo}}{% endblock %}
{% block site_keywords %}{{section.metatag.keywords}}{% endblock %}
{% block site_description %}{{section.metatag.descripcion|safe}}{% endblock %}

{% block metatags %}
<!--Facebook-->
<meta property="og:url"         content="http://quepadreserpadres.com" />
<meta property="og:type"        content="" />
<meta property="og:title"       content="{{section.metatag.titulo}}" />
<meta property="og:description" content="{{section.metatag.descripcion|striptags|safe}}" />
<meta property="og:image"       content="" />
<!--Twiter-->
<meta name="twitter:card"       value="">
<meta name="twitter:creator"    value="Punk e-Marketing & Consulting">
<meta name="twitter:url"        value="http://quepadreserpadres.com">
<meta name="twitter:title"       value="{{section.metatag.titulo}}">
<meta name="twitter:description" value="{{section.metatag.descripcion|striptags|safe}}" />
<meta name="twitter:image"       value="">
{% endblock %}

{% block content %}
	<section class="slider-content row">
		<div class="container-fluid withinpadding">
			<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="3000" id="bs-carousel">
			  <!-- Overlay -->
			  <!--div class="overlay"></div-->
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			  </ol>
			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			  	{% for slide_item in section.category_slide.sectionslideitem_set.all %}
			  		<div class="item slides">
				      <div class="slide-1">
				      	<img src="/media/{{ slide_item.image }}" class="img-responsive" alt="{{ slide_item.titulo|safe }}" title="{{ slide_item.titulo|safe }}">
				      </div>
				      <div class="hero col-md-5 col-sm-5">
				        <hgroup>
				            <h2>{{ slide_item.titulo }}</h2>        
				            <p>{{ slide_item.descripcion|safe|truncatewords:12 }}...</p>
				        </hgroup>
				        <a href="/{{ slide_item.slide_url }}" style="color:white">
				        	<button class="btn btn-hero btn-lg" role="button">IR AL ARTÍCULO</button>
			        	</a>
				      </div>
				    </div>
			  	{% endfor %}
			  </div> 
			</div>
		</div>
	</section>
	<section class="articles-content row">
		<div class="container">
			<div class="col-md-9 col-sm-9 col-xs-12">
				<div class="row">
					<h1 class="text-center page-title">{{section.name}}</h1>
				</div>
				<!-- <h1>Choose your favorite module</h1> -->
				<div class="row">
					<div class="col-md-12 list_of_articles">
						{% for new in noticias %}
							<div class="col-md-6 col-sm-6 col-xs-12 article-item">
								<a href="{%url 'news_detail' new.categoria.slug new.slug %}">
									<img src="/media{{ new.imagen_thumbnail }}" class="img-responsive">
								</a>
								<div class="article-description">
									<h2 class="text-center news-title">{{ new.titulo|safe }}</h2>
									<p>{{ new.texto1|safe|truncatewords:20 }}</p>
									<p class="text-center"><a href="">LEER MÁS</a></p>
								</div>
							</div>
							{% if forloop.counter|divisibleby:3 %}
								<div class="col-md-6 col-sm-6 col-xs-12 article-item text-center">
									<img src="{% static 'imgs/general/hijos/game-icon.png' %}" class="img-cat" alt="{{ section.titulo }}" title="{{ section.titulo }}">
								</div>
							{% endif %}	
							{% if forloop.counter|divisibleby:5 %}
								<div class="col-md-6 col-sm-6 col-xs-12 article-item text-center cat-img-icon">
									<img src="{% static 'imgs/general/hijos/toy-icon.png' %}" class="img-cat" alt="{{ section.titulo }}" title="{{ section.titulo }}">
								</div>
							{% endif %}	
						{% endfor %}
					</div>
				</div>
				{% if is_paginated %}
				<div class="row text-center">
				  <ul class="pagination">
				    {% if page_obj.has_previous %}
				      <li><a href="?page={{ page_obj.previous_page_number }}"><i class="icon-triangle-left"></i></a></li>
				    {% else %}
				      <li class="disabled"><a href="#"><i class="icon-triangle-left"></i></a></li>
				    {% endif %}

				    {% for num in page_obj.paginator.page_range %}
				      {% ifequal num page_obj.number %}
				        <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
				      {% else %}
				        <li><a href="?page={{ num }}">{{ num }}</a></li>
				      {% endifequal %}
				    {% endfor %}

				    {% if page_obj.has_next %}
				      <li><a href="?page={{ page_obj.next_page_number }}"><i class="icon-triangle-right"></i></a></li>
				    {% else %}
				      <li class="disabled"><a href="#"><i class="icon-triangle-right"></i></a></li>
				    {% endif %}
				  <ul>
				</div>
				{% endif %}
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				{% include "rightbar.html" %}  
			</div>
		</div>
	</section>	
{% endblock %}
{% block js %}
<script type="text/javascript">
$('.carousel .carousel-inner .item:eq(0)').addClass('active');
for (var i=1; i<=$("#fullpageservices").children().length;i++)
{
    var parimpar ="par";
    if(i%2){
        parimpar = "impar";
    }
    $('#fullpageservices .fp-tableCell .items:eq('+(i-1)+')').addClass('row-'+parimpar);
}
//alert('{{section.section_slide.sectionslideitem_set.all.count}}');
var slide_length = '{{section.category_slide.sectionslideitem_set.all.count}}';
for ( var i = 0; i < slide_length; i++ ){
	$('.carousel-indicators').append('<li data-target="#bs-carousel" data-slide-to="'+i+'" class=""></li>');
}
$('ol.carousel-indicators li:eq(0)').addClass('active');
$(function() {
	$('nav a[href^="/' + location.pathname.split("/")[1] + '"]').addClass('active');
});

$('.list_of_articles .article-item:last').css('display','none');
</script>
{% endblock %}

main/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ section.metatag.titulo }}{% endblock %}
{% block site_title %}{{section.metatag.titulo}}{% endblock %}
{% block site_keywords %}{{section.metatag.keywords}}{% endblock %}
{% block site_description %}{{section.metatag.descripcion|safe}}{% endblock %}

{% block metatags %}
<!--Facebook-->
<meta property="og:url"         content="http://quepadreserpadres.com" />
<meta property="og:type"        content="" />
<meta property="og:title"       content="{{section.metatag.titulo}}" />
<meta property="og:description" content="{{section.metatag.descripcion|striptags|safe}}" />
<meta property="og:image"       content="" />
<!--Twiter-->
<meta name="twitter:card"       value="">
<meta name="twitter:creator"    value="Punk e-Marketing & Consulting">
<meta name="twitter:url"        value="http://quepadreserpadres.com">
<meta name="twitter:title"       value="{{section.metatag.titulo}}">
<meta name="twitter:description" value="{{section.metatag.descripcion|striptags|safe}}" />
<meta name="twitter:image"       value="">
{% endblock %}

{% block bodyclass %}qpsp-home{% endblock %}
{% block content %}
	<section class="slider-content row">
		<div class="container-fluid withinpadding">
			<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="3000" id="bs-carousel">
			  <!-- Overlay -->
			  <!--div class="overlay"></div-->
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			  </ol>
			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			  	{% for slide_item in section.section_slide.sectionslideitem_set.all %}
			  		<div class="item slides">
				      <div class="slide-1">
				      	<img src="/media/{{ slide_item.image }}" class="img-responsive" alt="{{ slide_item.titulo|safe }}" title="{{ slide_item.titulo|safe }}">
				      </div>
				      <div class="hero col-md-5 col-sm-5">
				        <hgroup>
				            <h2>{{ slide_item.titulo }}</h2>        
				            <p>{{ slide_item.descripcion|safe|truncatewords:12 }}...</p>
				        </hgroup>
				        <a href="{{ slide_item.slide_url }}" style="color:white">
				        	<button class="btn btn-hero btn-lg" role="button">IR AL ARTÍCULO</button>
			        	</a>
				      </div>
				    </div>
			  	{% endfor %}
			  </div> 
			</div>
		</div>
	</section>
	<section class="articles-content row">
		<div class="container">
			<div class="col-md-9 col-sm-9 col-xs-12">
				<div class="row">
					<h1 class="text-center page-title">ARTÍCULOS</h1>
					
				</div>
				<!-- <h1>Choose your favorite module</h1> -->
				<div class="row">
					<div class="col-md-12 list_of_articles">
						{% for new in news %}
							<div class="col-md-6 col-sm-6 col-xs-12 article-item">
								<a href="{% url 'news_detail' new.categoria.slug new.slug %}">
									<img src="/media{{ new.imagen_thumbnail }}" class="img-responsive">
								</a>
								<div class="article-description">
										<h2 class="text-center news-title">{{ new.titulo|safe }}</h2>
									<p>{{ new.texto1|striptags|safe|truncatewords:20 }}</p>
									<p class="text-center"><a href="">LEER MÁS</a></p>
								</div>
							</div>
							{% if forloop.counter|divisibleby:3 %}
								<div class="col-md-6 col-sm-6 col-xs-12 article-item text-center">
									<img src="{% static 'imgs/general/home/icon-1.png' %}" class="img-cat" alt="{{ section.titulo }}" title="{{ section.titulo }}">
								</div>
							{% endif %}	
							{% if forloop.counter|divisibleby:5 %}
								<div class="col-md-6 col-sm-6 col-xs-12 article-item text-center">
									<img src="{% static 'imgs/general/home/icon-2.png' %}" class="img-cat" alt="{{ section.titulo }}" title="{{ section.titulo }}">
								</div>
							{% endif %}	
						{% endfor %}
					</div>
				</div>

				{% if is_paginated %}
				<div class="row text-center">
				  <ul class="pagination">
				    {% if page_obj.has_previous %}
				      <li><a href="?page={{ page_obj.previous_page_number }}"><i class="icon-triangle-left"></i></a></li>
				    {% else %}
				      <li class="disabled"><a href="#"><i class="icon-triangle-left"></i></a></li>
				    {% endif %}

				    {% for num in page_obj.paginator.page_range %}
				      {% ifequal num page_obj.number %}
				        <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
				      {% else %}
				        <li><a href="?page={{ num }}">{{ num }}</a></li>
				      {% endifequal %}
				    {% endfor %}

				    {% if page_obj.has_next %}
				      <li><a href="?page={{ page_obj.next_page_number }}"><i class="icon-triangle-right"></i></a></li>
				    {% else %}
				      <li class="disabled"><a href="#"><i class="icon-triangle-right"></i></a></li>
				    {% endif %}
				  <ul>
				</div>
				{% endif %}

			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				{% include "rightbar.html" %}  
			</div>
		</div>
	</section>	
{% endblock %}
{% block js %}
<script type="text/javascript">
	$('.list_of_articles .article-item:last').css('display','none');
	$('.carousel .carousel-inner .item:eq(0)').addClass('active');
	for (var i=1; i<=$("#fullpageservices").children().length;i++)
    {
        var parimpar ="par";
        if(i%2){
            parimpar = "impar";
        }
        $('#fullpageservices .fp-tableCell .items:eq('+(i-1)+')').addClass('row-'+parimpar);
    }
	//alert('{{section.section_slide.sectionslideitem_set.all.count}}');
	var slide_length = '{{section.section_slide.sectionslideitem_set.all.count}}';
	for ( var i = 0; i < slide_length; i++ ){
		$('.carousel-indicators').append('<li data-target="#bs-carousel" data-slide-to="'+i+'" class=""></li>');
	}
	$('ol.carousel-indicators li:eq(0)').addClass('active');

	$('ul.main-menu li a').removeClass('active');
	$('ul.main-menu li a.menu-').removeClass('active');
	$('.menu-home').addClass('active');
</script>
{% endblock %}

main/templates/rightbar.html
<div class="row no-margin">
	<h3 class="text-center right-bar-title">ARTÍCULOS MÁS LEÍDOS</h3>
	<ol class="most-viewed-articles">
	{% for item in list_most_viewed %}

		<li><a href="{%url 'news_detail' item.categoria.slug item.slug %}">{{item.titulo}} <i class="icon-triangle-right"></i></a></li>
	{% endfor %}
	</ol>
</div>
<hr class="row right-separator">
<div class="row latest_videos no-margin">
	<h3 class="text-center right-bar-title" style="margin-bottom:15px;">VIDEOS</h3>
	<ul>
	{% for video in latest_videos %}
		<li>
			<a href="https://www.youtube.com/watch?v={{ video.id_video }}" class="video">
				<img src="http://img.youtube.com/vi/{{ video.id_video }}/hqdefault.jpg" class="img-responsive">
				<i class="icon-triangle-right"></i>
			</a>
		</li>
	{% endfor %}
		<li class="ver-mas-videos">
			<a href="{% url 'videos_view' %}"><strong>ver todos los videos</strong></a>
		</li>
	</ul>
</div>
<hr class="row right-separator">
<div class="row no-margin">
	<h3 class="text-center right-bar-title" style="margin-bottom:15px;">¿QUIERES RECIBIR LA REVISTA DE MANERA SEMANAL?</h3>
	<div class="cd-form-wrapper cd-container">
		<form class="cd-form">
			<label class="cd-label" for="cd-email">SUSCRÍBETE</label>
			<input type="email" id="cd-email" class="cd-email" name="cd-email" placeholder="Ingresa tu correo electrónico">
			<input type="submit" class="cd-submit" value="ENVIAR">
			<div class="cd-loading"></div>
		</form>
		<input style="display:none" type="radio" id="cd-success" name="cd-message" checked>
		<!--input type="radio" id="cd-error" name="cd-message"-->
		<!--div data-type="message" class="cd-response cd-response-error">Ops! Error message here</div-->
		<div data-type="message" class="cd-response-success"><p>Gracias por suscribirte, ¡pronto recibirás nuevas noticias!</p></div>
		<!--div data-type="message" class="cd-response cd-response-notification">Hey! Notification message here</div-->
	</div>
</div>
<hr class="row right-separator">
<div class="row no-margin">
	{% for banner in section.banner.banneritem_set.all %}
		<a href="{{ banner.slide_url }}" target="_blank">
			<img src="/media/{{ banner.image }}" class="img-responsive">
		</a>
		<br>
	{% endfor %}
</div>
<hr class="row right-separator">
<div class="row event-content no-margin">
	<h3 class="text-center right-bar-title" style="margin-bottom:15px;">QPSP TE INVITA A:</h3>
	<ul class="events">
		<li class="ev-first"><a href="https://www.facebook.com/QPSPacapulco/" target="_blank">ACAPULCO</a></li>
		<li class="ev-second"><a href="https://www.facebook.com/QPSP-Canc%C3%BAn-te-invita-289433958076446/" target="_blank">CANCÚN</a></li>
		<li class="ev-third"><a href="https://www.facebook.com/QPSP-Riviera-Maya-te-invita-1609426432700743/" target="_blank">RIVIERA MAYA</a></li>
	</ul>
</div>
{% block js %}

{% endblock %}